config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root to: "welcome#index"
  devise_for :users
  resources :premiums
  resources :subscriptions
	  # collection do
	  #     get :manage_subscription , as: :manage_subscription
	  # end
	# end
  get '/manage_subscription', to: 'subscriptions#manage_subscription', as: :manage_subscription
  get '/unsubscribe', to: 'subscriptions#unsubscribe_plan', as: :unsubscribe

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token
end

app/controllers/premiums_controller.rb
require 'stripe'
class PremiumsController < ApplicationController
	def index
		subscribe(current_user) if current_user.present?
		respond_to do |format|
      format.js { render js: "alert('Success')" }
      format.html { redirect_to subscriptions_path}
    end
	end

	private

	### Create Customer ###
	def create_customer(user)
		 customer = Stripe::Customer.create({
  		description: "My First Test Customer #{current_user.email}",
  		email: "#{current_user.email}"
			}) 
		p "====================== Customer: #{customer.id} ==================="
		return customer
	end

  ### Create Customer Plan ###
	def customer_plan(user)
		 cust_plan = Stripe::Plan.create({
			  amount: 250,
			  currency: 'usd',
			  interval: 'month',
			  product: {name: "#{current_user.email} product"},
			})
	 	p "====================== Plan: #{cust_plan.id} ==================="
	 	return cust_plan
	end

	### Create Source ###
	def create_source(user)
		source = Stripe::Source.create({
		  type: 'ach_credit_transfer',
		  currency: 'usd',
		  owner: {
		    email: "#{current_user.email}",
		  },
		})
		p "====================== Source: #{source.id} ==================="
		return source
	end

	###  Attaching source to existing customer ###
	def attaching_source_to_existing_user(user,customer,source)
		attaching_source = Stripe::Customer.create_source(
		  "#{customer.id}",
		  {
		    source: "#{source.id}",
		  }
		)
		p "====================== Source: #{attaching_source.id} ==================="
		return attaching_source
	end

	### create subscription
	def subscribe_user(user,customer,cust_plan)
		subscription = Stripe::Subscription.create({
    customer: "#{customer.id}",
    items: [
		        {
		            plan: "#{cust_plan.id}",
		            quantity: 1,
		        },
	    		],
		})
		p "====================== Subscription: #{subscription.id} ==================="
		return subscription
	end

	def subscribe(user)
		Stripe.api_key = ENV['STRIPEAPIKEY']
		customer = create_customer(user)
		cust_plan = customer_plan(user)
		source = create_source(user)
		attaching_source = attaching_source_to_existing_user(user,customer,source)
		subscription = subscribe_user(user,customer,cust_plan)
	end
end

app/controllers/subscriptions_controller.rb
require 'stripe'
require 'uri'
require 'net/http'
require 'json'

class SubscriptionsController < ApplicationController
	def index
	end

	def unsubscribe_plan
		subscription = Stripe::Subscription.delete(params[:subscription_id]) if params[:subscription_id].present?
		redirect_to manage_subscription_path
	end

	def manage_subscription
		@customer_ids = fetch_customer
		@subscriptions = login_user_subscription(@customer_ids)
	end 

	private

	def fetch_customer
		Stripe.api_key = ENV['STRIPEAPIKEY']
		user_email = current_user.email
		url = URI("https://api.stripe.com/v1/search?query='#{user_email}'&prefix=false")

		http = Net::HTTP.new(url.host, url.port)
		http.use_ssl = true
		http.verify_mode = OpenSSL::SSL::VERIFY_NONE

		request = Net::HTTP::Get.new(url)
		request["content-type"] = 'application/json'
		request["authorization"] = "Bearer #{ENV['STRIPE_AUTHORIZATION']}"

		response = http.request(request)
	  	result  =JSON.parse(response.body)
		result = result["data"]
		@res_arr = []
		result.each do |i|
		 @res_arr << i["id"] if i["object"] == "customer"
		end
		return @res_arr
	end

	def login_user_subscription(customer_ids)
		Stripe.api_key = ENV['STRIPEAPIKEY']
		subscriptions = Stripe::Subscription.list()
		subscriptions = subscriptions["data"]
		@subs_list = [] 
		subscriptions.each do |sub|
			@subs_list << sub if customer_ids.include? sub["customer"]
		end
		return @subs_list
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/premiums_helper.rb
module PremiumsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HnrTech</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  	<img src="https://cdn2.iconfinder.com/data/icons/scrum-project-blue/100/User_Testing-512.png"  alt="Subscription"  class="main-image">
<h2 class="center">Welcome To Ruby Subscription</h2>
    <%= yield %>
  </body>
</html>

app/views/subscriptions/index.html.erb
<div class="center">
	<% if user_signed_in? %>
		<li>
			<%= link_to('Logout', destroy_user_session_path, method: :delete) %> |  
			<%= link_to('Manage Subscription', manage_subscription_path) %> | 
			<%= link_to('Premium', root_path) %>
		</li>
	<% else %>
		<li>
	  	<%= link_to('Login', new_user_session_path) %> |
	  	<%= link_to('Register', new_user_registration_path) %>
	  </li>
	<% end %>
</div>

app/views/subscriptions/manage_subscription.html.erb
<td><%= link_to "Home",root_path %>
<table border= "1">
  <thead>
    <tr>
      <th>Subscription ID</th>
      <th>Current Period Start</th>
      <th>Current Period End</th>
      <th>Customer id</th>
      <th>Plan id</th>
      <th> Quantity</th>
      <th>Currency</th>
      <th>Amount </th>
      <th>Interval</th>
      <th>Plan Staus</th>
      <th>Action</th>
    </tr>
  </thead>
 
  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= subscription.id %></td>
        <td><%= Time.at(subscription.current_period_start).strftime("%d/%m/%Y %k:%M") %></td>
        <td><%= Time.at(subscription.current_period_end).strftime("%d/%m/%Y %k:%M") %></td>
        <td><%= subscription["customer"] %></td>
        <td><%= subscription["plan"]["id"] %></td>
        <td><%= subscription["quantity"] %></td>
        <td><%= subscription["plan"]["currency"] %></td>
        <td><%= subscription["plan"]["amount"] %></td>
        <td><%= subscription["plan"]["interval"] %></td>
        <td><%= subscription["plan"]["active"]== true ? "Active" : "Inactive" %></td>
        <td><%= link_to "Unsubscribe", unsubscribe_path(:subscription_id => subscription.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/welcome/index.html.erb
<div class="center">
	<% if user_signed_in? %>
		<li>
			<%= link_to('Logout', destroy_user_session_path, method: :delete) %> |  
			<%= link_to('Go Premium', premiums_path, title: "Price: $250 USD / month") %>
		</li>
	<% else %>
		<li>
	  	<%= link_to('Login', new_user_session_path) %> |
	  	<%= link_to('Register', new_user_registration_path) %>
	  </li>
	<% end %>
</div>